[package]
name = "ci-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sequential-test = { path = "../sequential-test" }
serial_test = "0.7.0"
rand = "0.8.5"

